"use client"

import { Card, CardContent } from "@/components/ui/card"
import {
  Network,
  Brain,
  ShieldCheck,
  BarChart3,
  MessageSquareLock,
  Bell,
  FileText,
  Lock,
} from "lucide-react"

const features = [
  {
    icon: Network,
    title: "Live Org-Chart Sync",
    description:
      "Automatically syncs your org structure via Microsoft Graph. Reporting lines, departments, and teams stay current without manual input.",
  },
  {
    icon: Brain,
    title: "AI Question Generation",
    description:
      "Role-aware, competency-mapped questions generated by AI with human review controls. No more generic feedback forms.",
  },
  {
    icon: BarChart3,
    title: "Narrative AI Summaries",
    description:
      "AI-generated result narratives with built-in bias detection, benchmarking against role cohorts, and actionable development insights.",
  },
  {
    icon: MessageSquareLock,
    title: "Always-On Anonymous Link",
    description:
      "Every employee gets a permanent anonymous feedback link. Volume thresholds ensure feedback cannot be traced to individuals.",
  },
  {
    icon: Bell,
    title: "Automated Distribution",
    description:
      "Smart reminders via Teams and email. Configurable cadence, escalation paths, and completion tracking built in.",
  },
  {
    icon: ShieldCheck,
    title: "POPIA/GDPR Compliance",
    description:
      "Full audit trails, configurable retention controls, consent management, and encrypted data handling aligned with SA and EU regulations.",
  },
  {
    icon: FileText,
    title: "Configurable Dashboards",
    description:
      "Role-based reporting views for HR, managers, and employees. Filter by department, cycle, competency, or time period.",
  },
  {
    icon: Lock,
    title: "Azure AD SSO",
    description:
      "Single sign-on via Azure Active Directory. No separate passwords, seamless provisioning, and automatic deprovisioning.",
  },
]

export function FeaturesSection() {
  return (
    <section className="bg-card py-24">
      <div className="mx-auto max-w-7xl px-6">
        <div className="mx-auto max-w-2xl text-center">
          <p className="text-sm font-semibold uppercase tracking-widest text-primary">
            Platform Capabilities
          </p>
          <h2 className="mt-2 text-balance text-3xl font-bold tracking-tight text-card-foreground sm:text-4xl">
            Everything you need for meaningful 360 feedback
          </h2>
          <p className="mt-4 text-pretty text-muted-foreground leading-relaxed">
            Deeply integrated with Microsoft 365, powered by AI, and built with privacy at its core.
          </p>
        </div>

        <div className="mx-auto mt-16 grid max-w-5xl gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {features.map((feature) => (
            <Card
              key={feature.title}
              className="group border-border bg-background transition-all hover:border-primary/30 hover:shadow-md"
            >
              <CardContent className="p-6">
                <div className="mb-4 flex size-10 items-center justify-center rounded-lg bg-primary/10">
                  <feature.icon className="size-5 text-primary" />
                </div>
                <h3 className="text-sm font-semibold text-foreground">
                  {feature.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  {feature.description}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  )
}
